#nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: appstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
      - name: app-ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.8.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: app-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-ui
