apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: nginx
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/success-codes: "200-499"
    alb.ingress.kubernetes.io/target-type: 'ip'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/subnets: subnet-095e01e5444585e4e, subnet-085bd087e28978b7d
spec:
  ingressClassName: alb
  rules:
  - host: sinovuyo.851725616318.realhandsonlabs.net
    http:
      paths:
      - path: /dev
        pathType: Prefix
        backend:
          service:
           name: nginx-service
           port:
            number: 80
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
             number: 8080
      - path: /home
        pathType: Prefix
        backend:
          service:
           name: catalog
           port:
            number: 80
