#ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: nginx
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/target-type: 'ip'
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    alb.ingress.kubernetes.io/scheme: internet-facing
    # still need to fix the the default action to forward to TG
    #alb.ingress.kubernetes.io/actions.default: >
     # {"Type": "forward", "ForwardConfig": {"TargetGroups": [{"ServiceName": "nginx-service", "ServicePort": "80"}]}}
    alb.ingress.kubernetes.io/subnets: "subnet-073b05c3e735dba6b", "subnet-05222976c49e763cb", "subnet-048287d7fc8d46dd4"
spec:
  ingressClassName: alb
  rules:
  - host: sinovuyo.730335617397.realhandsonlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: nginx-service
           port:
            number: 80
