#serive account for the ingress controller
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  #update the policy ARN fron the sh script
    eks.amazonaws.com/role-arn: arn:aws:iam::339712811345:role/AmazonEKSLoadBalancerControllerRole
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: aws-load-balancer-controller-dev
  namespace: kube-system
