name: Application CI/CD

on:
  push:
    branches:
    #watches changes on terraform branch merges
      - dev-application

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Access eks Cluster
        run: |
            # install ArgoCD in k8s
            kubectl create namespace argocd
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
            
            # access ArgoCD UI
            kubectl get svc -n argocd
            #kubectl port-forward svc/argocd-server 8080:443 -n argocd
            
            # login with admin user and below token (as in documentation):
            kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode && echo
            
            # you can change and delete init password

